# Generated by Django 3.2.5 on 2021-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('ibi', models.IntegerField()),
                ('mysignal', models.IntegerField()),
            ],
            options={
                'db_table': 'new_table',
            },
        ),
        migrations.CreateModel(
            name='Serial_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'serial',
            },
        ),
    ]
